### PR TITLE
fix: Added firebase and express to filters

### LINKED ISSUE #1735: feat:Addition of Express and Firebase in the filters
### What feature?

As an express dev i think adition of express and firebase will great

### Add screenshots

Screenshot 2023-07-16 at 10 36 58 PM

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Sahilll15**
## Related Issue
Closes #1735 
Title: Addition of Express and Firebase to Filters

Description
This pull request adds Express and Firebase to the existing list of technologies in the utils/techStack.ts file. The techStack array now includes the following technologies:

const techStack = [
  "reactjs",
  "nodejs",
  "nextjs",
  "javaScript",
  "python",
  "mongodb",
  "typescript",
  "express",
  "firebase"
];

Please review and merge this pull request to incorporate these changes into the project.

Screenshots:-
earlier:-
Screenshot 2023-07-16 at 10 36 58 PM

updated:-
Screenshot 2023-07-17 at 12 49 47 AM

### CODE REVIEW

**Comment by Sahilll15** [comment]
@priyankarpal have a look!!

File: utils/techStack.ts [hunk 1]
```diff
@@ -6,6 +6,8 @@ const techStack = [
   "python",
   "mongodb",
   "typescript",
+  "express",
```
Comment (priyankarpal) [inline utils/techStack.ts:9]: rename to `expressjs`
```suggestion
  "expressjs",
```

**Review by priyankarpal — CHANGES_REQUESTED** [review]

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉
